### ISSUE TITLE
Using another name as 'default' for token client throws exception?

### ISSUE THREAD

**Issue by StefH** [IdentityModel/IdentityModel.AspNetCore#134]
I've this code:
``` c#
.ConfigureServices((hostContext, services) =>
{
    services.AddAccessTokenManagement(options =>
    {
        options.Client.Clients.Add("AzureAD", new ClientCredentialsTokenRequest
        {
            Address = $"https://login.microsoftonline.com/{ten}/oauth2/token",
            ClientId = id,
            ClientSecret = secret,
            GrantType = "client_credentials",

            Scope = Scope1,

            Parameters =
            {
                { "resource", "821eb724-edb8-4dba-b425-3f953250c0ae" }
            }
        });
    });

    // custom name is used here:
    services.AddClientAccessTokenClient("client", "my-token-client", configureClient: client =>
    {
        client.BaseAddress = new Uri("https://localhost:5001");
    });

    services.AddHostedService<Worker>();
});
```

And the code to send the http get request:
``` c#
var client = _clientFactory.CreateClient("client");
var response = await client.GetAsync("weatherforecast", stoppingToken);
```

```
[12:11:58 DBG] Cache miss for access token for client: my-token-client
Unhandled exception. System.InvalidOperationException: No access token client configuration found for client: my-token-client
   at IdentityModel.AspNetCore.AccessTokenManagement.DefaultTokenClientConfigurationService.GetClientCredentialsRequestAsync(String clientName)
   at IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.RequestClientAccessToken(String clientName)
   at IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService.<>c__DisplayClass9_0.<<GetClientAccessTokenAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService.GetClientAccessTokenAsync(String clientName, Boolean forceRenewal)
   at IdentityModel.AspNetCore.AccessTokenManagement.ClientAccessTokenHandler.SetTokenAsync(HttpRequestMessage request, Boolean forceRenewal)
   at IdentityModel.AspNetCore.AccessTokenManagement.ClientAccessTokenHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by leastprivilege** [comment]
Don't you want to do this:

```
    services.AddClientAccessTokenClient("client", "AzureAD", configureClient: client =>
    {
        client.BaseAddress = new Uri("https://localhost:5001");
    });
```

?

**Comment by StefH** [comment]
@leastprivilege 
Correct this is indeed the intended usage.
Thank you.
