### ISSUE TITLE
Issue with using await and continue with

### ISSUE THREAD

**Issue by Rushman1** [IdentityModel/IdentityModel.AspNetCore#68]
Good Afternoon,

I was wondering if anyone else has run into this error: I have a list of objects (classes with several public properties) and I an trying to iterate over them and call a method on my API async-ly and then use ContinueWith to call the API again (different method) to do some db maintenance in order (I am updating a table and when that is done, I am updating a different table). But I keep getting a null reference exception in the GetUserAccessTokenAsync method.

Here is a section of my error log. (I changed the namespace to fit my application - TcrWeb)

2020-02-06 15:36:45.163 -08:00 [Information] Message Added: 2/6/2020 3:36:45 PM, Log ID: 33, AccessToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1NDc0REJFQkZENUU4MDlFQjhFODZCRTExRUZFNDAwNjA4REM2QTQiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJoVWROdnJfVjZBbnJqb2EtRWVfa0FHQ054cVEifQ.eyJuYmYiOjE1ODEwMzIxOTgsImV4cCI6MTU4MTAzNTc5OCwiaXNzIjoiaHR0cHM6Ly90Y3Itc3RnLmhjcG52LmNvbSIsImF1ZCI6InRjci1hcGkiLCJjbGllbnRfaWQiOiJ0Y3Itd2ViIiwic3ViIjoiMiIsImF1dGhfdGltZSI6MTU4MTAyNzMxOSwiaWRwIjoibG9jYWwiLCJuYW1lIjoiVGltIFNhdmFnZSIsInByZWZlcnJlZF91c2VybmFtZSI6InRpbW90aHkuc2F2YWdlIiwiZW1haWwiOiJ0c2F2YWdlQGhjcG52LmNvbSIsInJvbGVfbGlzdCI6InN1cGVyX3VzZXIiLCJ1c2VyX2lkIjoiMiIsImZ1bGxfbmFtZSI6IlRpbSBTYXZhZ2UiLCJjbGluaWNfbGlzdCI6IjM0LDM3LDM4LDUwLDUxLDUyLDU1LDU2LDU3LDU4LDU5LDYxLDYzLDY0LDY2LDY5LDcwLDcyLDc0LDc1LDc2LDc3LDc5LDgwLDgxLDgyLDgzLDg3LDg5LDkyLDkzLDk1LDk2LDk3LDEwMSwxMDMsMTc1LDE3OCwxODUsMTg2LDE4OSwxOTAsMTkzLDE5NCwxOTcsMjAyLDIwNCwyMDUsMjA2LDIwNywyMTAsMjI2LDIyNywyMjgsMjI5LDIzMSwyMzMsMjM1LDEsMywxMywxNCwxNiwxOCwxOSwyMCwyMSwyMiwyMywyOSwzMSIsImNsaW5pY19pZCI6IjM0IiwibGFzdF9sb2dpbiI6IjAyLzA2LzIwMjAgMTQ6MTU6MTkiLCJhcF9hcHByb3ZhbF9sZXZlbCI6IjQwIiwidXNlcl9zZXNzaW9uX2lkIjoiMzc2NmRlNmQtZTY0My00NjRmLThiOTQtMTQxMTljMGJlMTNkIiwiYWRkcmVzcyI6IjcwMCBFIFdhcm0gU3ByaW5ncyBSZC4gTGFzIFZlZ2FzLCBOViA4OTExOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ0aW1vdGh5LnNhdmFnZSIsInNjb3BlIjpbInByb2ZpbGUiLCJvcGVuaWQiLCJ0Y3ItYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.oujbYTtsZy60XUoHECeP2bEys2wAYwlTHrfjVmLFAKuN9u67ZXnHpV9iNfbS1R69qEisJsrE7ZPh-WIVw73VxiEZyjHMeAbZ2MmEmJKRSUcq0fRwSi70gyQarjgGmir1_EtQvskLGGHyYaLV3Mpuqbv4HTJy7_94P_rrhj7kYu-w_2E1614pK7LeP0PKJbK22jcWdGrXVsqSRPcBCdQP9DQuLlyu5hZD-ecC0jqkQtAAsK_qAQvmy3jiv00z_KNyYLe4nmznPm1tP9PCltQmY6a31j-ZK7gCfMQkh69Rmxaum5o1r7URG7HXem9a-8eKC3ljNW2GIxyOb3z1uuTRjw
Checking if Client is available: True
(THIS LINE IS WHAT MY OBJECT HOLDS)
Encounter Log: Id:33,Campaign:2010,comment:,LogStatus:3,UserId:2,DateOfDischarge:
Error: Object reference not set to an instance of an object. -- StackTrace:    at TcrWeb.TokenManagementHttpContextExtensions.GetUserAccessTokenAsync(HttpContext context, Boolean forceRenewal) in C:\Code\WebApps\TcrWeb\TcrWeb\AccessTokenManagement\TokenManagementHttpContextExtensions.cs:line 23
   at TcrWeb.UserAccessTokenHandler.SetTokenAsync(HttpRequestMessage request, Boolean forceRenewal) in C:\Code\WebApps\TcrWeb\TcrWeb\AccessTokenManagement\UserAccessTokenHandler.cs:line 54
   at TcrWeb.UserAccessTokenHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Code\WebApps\TcrWeb\TcrWeb\AccessTokenManagement\UserAccessTokenHandler.cs:line 31
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at TcrWeb.EncounterDbService.MaintainEncounter(EncounterLog log, String accessToken) in C:\Code\WebApps\TcrWeb\TcrWeb\Services\EncounterDbService.cs:line 166

2020-02-06 15:37:21.511 -08:00 [Information] "Cookies" was not authenticated. Failure message: "Unprotect ticket failed"
2020-02-06 15:37:21.515 -08:00 [Information] AuthenticationScheme: "oidc" was challenged.

If you need anything else from me, please don't hesitate to let me know.

Thank you ,
Tim

**Comment by leastprivilege** [comment]
> 2020-02-06 15:37:21.511 -08:00 [Information] "Cookies" was not authenticated. Failure message: "Unprotect ticket failed"

This looks like to root cause to me.

**Comment by Rushman1** [comment]
I would say so as well. How do I get around that issue, and why does it happen only when I am using the Async/ContinueWith patterns?

**Comment by leastprivilege** [comment]
I don't know.

**Comment by duckblaster** [comment]
Are you awaiting the results of the ContinueWith?
